### ISSUE TITLE
Compat section missing from project file

### ISSUE THREAD

**Issue by JanisErdmanis** [hardbyte/Paillier.jl#15]
Currently, AutoMerge complains that there is no [compat] section in the Project file as in my case:
https://github.com/JuliaRegistries/General/pull/4907

**Comment by hardbyte** [comment]
I'm closing as I think AutoMerge complaint is referring to your Project.toml file. The Paillier one is [here](https://github.com/hardbyte/Paillier.jl/blob/master/Project.toml#L11)

Please reopen if I need to change something.
